import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { GetStaticProps } from 'next'
type result = {
  name :string,
  age: number,
  count: number
}

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data.name}
      {data.age}
      {data.count} 
      </>
  )
}

export const getStaticProps:GetStaticProps = async (context) => {
  const data = await fetch('https://api.agify.io/?name=mihir')
  const result : result = await data.json()

  
  
  return {
    props :{
      data: result
    }
  }
}